### ISSUE TITLE
Checking a user's inventory

### ISSUE THREAD

**Issue by kenthegreat8** [rbx-libdev/ro.py#14]
**Is your feature request related to a problem? Please describe.**
NO
**If your feature is related to implementing a new Roblox API, provide information here.**
API URL: https://users.roblox.com/v1/users/{userId}
Documented: Yes/No
no

**Describe the solution you'd like**

**Describe alternatives you've considered**
It would be cool if we could check a user's inventory for checking gamepasses or asset's and then from there, ranking them in your group.
**Additional context**

**Comment by jmkd3v** [comment]
Please format your future feature requests properly - you've left out or improperly formatted important information.
We have plans to implement inventory-related features in the next two releases.

**Comment by kenthegreat8** [comment]
> Please format your future feature requests properly - you've left out or improperly formatted important information.
> We have plans to implement inventory-related features in the next two releases.

Oh okay thanks and sorry for that. I'll fornat next time. I forgot to say, in checking the inventory, they can check for gamepasses, etc.
