### ISSUE TITLE
Advice for the rewrite

### ISSUE THREAD

**Issue by rbx-nsg** [rbx-libdev/ro.py#18]
There is an issue with production right now, there is little to no strong typing on anything.

All implementations for the rewrite should be strong typed, as it is supported.

The benefits of this include stronger intellisense.

If you look at my libraries they show strong typed code, with predicable interfaces, it is preferable to do this because it is more convenient than having to go to some documentation page.

![image](https://user-images.githubusercontent.com/79342039/117555813-4e2c3f80-b05a-11eb-8abf-1acea89def8d.png)
![image](https://user-images.githubusercontent.com/79342039/117555823-5d12f200-b05a-11eb-8781-9a4453d12a6a.png)

You can disregard this issue if you wish, but take it into mind.

**Comment by jmkd3v** [comment]
In the past, we have added some typing - but it was inconsistent and barely present. We plan to strongly type our code as much as possible in the rewrite.

**Comment by rbx-nsg** [comment]
Alrigt

**Comment by rbx-nsg** [comment]
tee hee
