### ISSUE TITLE
Problems with .join() and browser_tracker_id

### ISSUE THREAD

**Issue by iDenis124** [rbx-libdev/ro.py#28]
**Describe the bug**
When trying to launch a game I get this error
![pycharm64_RoMMnoEtNO](https://user-images.githubusercontent.com/51971218/125211967-d1fce500-e2b2-11eb-9425-645a79fcd6ac.png)

**To Reproduce**
Use `.join()` on a root game place

**Expected behavior**
Expected the game to start

**Additional context**
I am using the Bleeding Edge version as the stable one had the error in the screenshot
![pycharm64_099xeypO9t](https://user-images.githubusercontent.com/51971218/125211950-c1e50580-e2b2-11eb-9f2a-1dcaa0b1198d.png)

**Comment by Boegie19** [comment]
@iDenis124 Can you try to use the github version aka the newest of the newest 
pip3 install git+git://github.com/rbx-libdev/ro.py.git

If that does not solve the issue please send me the code you used so that I can use it to make a fixed version

**Comment by iDenis124** [comment]
Will do when I get home

**Comment by iDenis124** [comment]
I have removed then updated it, the `BrowserTrackerId` problem still persists

Here is the code
```python
import asyncio
from ro_py.client import Client

client = Client(
    token=r"_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|"
)


async def main():
    game = await client.get_game_by_place_id(47324)
    root = await game.get_root_place()
    await root.join()


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```
with my token removed, for obvious reasons

**Comment by Boegie19** [comment]
@iDenis124 I have run the code and on the 

pip3 install git+git://github.com/rbx-libdev/ro.py.git

version it works without any problems for me so I can't replicate on the last release version however it is broken.

If you have any more questions or need more help I recommend you to join the RoApi discord
https://discord.gg/vMdtQgVUk9

**Comment by iDenis124** [comment]
https://user-images.githubusercontent.com/51971218/125944470-e0b4f1ac-452e-42bb-9c05-dff8a9c9283b.mp4

The video shows me installing the latest version from git.

I don't have any more ideas, I also reinstalled Roblox and deleted the `appStorage.json` file from where it gets the `BrowserTrackerId` and launched a game in hope of it regenerating.

Maybe Roblox patched this method and it's still working on your machine since you have an old install with the needed file?

**Comment by Boegie19** [comment]
@iranathan Any ideas I am also going to do some testing to see if I can get it to work witout the ID

**Comment by Boegie19** [comment]
Okay I looked into it a little bit more made a special version for you that you can use until the main branch is updated with this pull request I just send

pip3 install git+git://github.com/Boegie19/ro.py.git@browser_tracker_fix

**Comment by iDenis124** [comment]
It works, thank you!
