### ISSUE TITLE
Calling group.get_member(id) errors

### ISSUE THREAD

**Issue by Zamdie** [rbx-libdev/ro.py#40]
**Describe the bug**
When calling `group.get_member(id)`, the following error is thrown:

![obraz](https://i.gyazo.com/158cb2ec79ce7dbe5b908fce4ebc3ec2.png)

**To Reproduce**
Call `.get_member(id)` on a group object.

**Expected behaviour**
Expected the call to not error and return a `Member` object.

**Additional context**
A request to https://groups.roblox.com/v2/users/{userId}/groups/roles is sent, and passed on to `Member`. It will attempt to index the `user` key on the data, which errors because the endpoint does not return that data.

![obraz](https://user-images.githubusercontent.com/74075188/137123768-2f8be354-e3f4-4be4-b957-7530f669ddc9.png)

**Comment by jmkd3v** [comment]
Closed by https://github.com/rbx-libdev/ro.py/commit/586b2e4b4e1be4d504f806393ddac2403cd44d8c.
